Objetivo0
francisco3207/IVProyecto pull request #1
Opened 2021-09-29 21:16 UTC by francisco3207

Tareas objetivo0

2021-10-01 05:25 UTC, JJ commented on README.md
> +Este proyecto está enfocado en realizar un microservicio en la nube enfocado en analizar articulos de moda. El cual visualizará su precio actual, su precio inicial, si está disponible el producto y e
Por favor, lee la descripción de este objetivo. 
* No debe tener detalles de implementación
* Debe describir un problema.
* Debe tener una lógica de negocio mínima.
* Su implementación más adecuada debe ser la nube.

2021-10-01 05:25 UTC, JJ commented on docs/README.md
> +![](imgs/crear_clave.png)
Mira el folleto de markdown para insertar las imágenes y/o el resultado de este comando en la web.

2021-10-02 07:47 UTC, JJ commented
¿Algún problema para seguir adelante con esto?

2021-10-02 18:07 UTC, francisco3207 commented
He cambiado la descripción del problema para que cumpla los requisitos.
Con respecto a la inserción de imágenes, he leido el seminario de markdown y no se si se refiere a ponerle un texto por si no se visualiza.

2021-10-03 07:02 UTC, JJ commented
> He cambiado la descripción del problema para que cumpla los requisitos. Con respecto a la inserción de imágenes, he leido el seminario de markdown y no se si se refiere a ponerle un texto por si no se visualiza.

Si, convendría que lo hicieras. Es una cuestión de usabilidad, pero también por supuesto descripción para los que lean el documento.

2021-10-03 07:06 UTC, JJ requested changes
Por favor, lee atentamente los comentarios, revisa el concepto de lógica de negocio (incluyendo el tutorial en vídeo) así como el guión de este objetivo.

2021-10-03 07:06 UTC, JJ commented on README.md
> +Actualmente existe una gran especulación con el mercado de la ropa y zapatillas de marcas limitadas, lo que conlleva también un gran mercado de falsificaciones por detrás.
Estoy un poco confundido con el problema a resolver. ¿Se trata de detectar falsificaciones?

2021-10-03 07:06 UTC, JJ commented on README.md
> +Este proyecto tratará de facilitar la compra y venta de estos artículos utilizándose como intermediario y analizando la procedencia del producto.
"Analizar" es una palabra clave que, en principio, correspondería a una lógica de negocio adecuada. Sin embargo, no tengo muy claro cómo se puede hacer esto desde un simple programa y qué lógica de negocio incluye "analizar la procedencia".

2021-10-03 07:06 UTC, JJ commented on README.md
> +El negocio lo encontraríamos en la comisión de compra por parte del comprador y la comisión de verificar la originalidad del producto por parte del vendedor.
Cuando se habla de lógica de negocio no se trata de decir de dónde se va a sacar el dinero (algo que estaría fuera del ámbito de la asignatura), aunque evidentemente la financiación del producto siempre da pistas sobre qué lógica de negocio se puede incluir. Se trata de incluir un procesamiento de datos no trivial que contribuya a resolver el problema del cliente. Eso es lo que tenéis que hacer para alcanzar este objetivo.

2021-10-04 15:57 UTC, francisco3207 commented on README.md
> +Actualmente existe una gran especulación con el mercado de la ropa y zapatillas de marcas limitadas, lo que conlleva también un gran mercado de falsificaciones por detrás.
Dar soporte a los usuarios de que la venta se haga correctamente, lo cual incluiría las falsificaciones.

2021-10-04 15:59 UTC, francisco3207 commented on README.md
> +Este proyecto tratará de facilitar la compra y venta de estos artículos utilizándose como intermediario y analizando la procedencia del producto.
Son productos que solo salen una vez a la venta, por lo que si sabemos de donde viene el producto y con su numero de serie verificaremos que sea verdadero.

2021-10-04 16:03 UTC, JJ commented on README.md
> +Actualmente existe una gran especulación con el mercado de la ropa y zapatillas de marcas limitadas, lo que conlleva también un gran mercado de falsificaciones por detrás.
Da soporte, ¿cómo?

2021-10-04 16:03 UTC, JJ commented on README.md
> +Este proyecto tratará de facilitar la compra y venta de estos artículos utilizándose como intermediario y analizando la procedencia del producto.
Si es así, no es analizar, es buscar. Si es sólo buscar, no es lógica de negocio. Por favor, repasa [el guión](http://jj.github.io/IV/documentos/proyecto/0.Repositorio)

2021-10-04 16:10 UTC, francisco3207 commented on README.md
> +Este proyecto tratará de facilitar la compra y venta de estos artículos utilizándose como intermediario y analizando la procedencia del producto.
Validar la procedencia si sería en ese caso no?

2021-10-04 16:14 UTC, francisco3207 commented on README.md
> +Actualmente existe una gran especulación con el mercado de la ropa y zapatillas de marcas limitadas, lo que conlleva también un gran mercado de falsificaciones por detrás.
Con dar soporte me refiero a hacerse cargo de la seguridad de la transacción

2021-10-04 16:21 UTC, JJ commented on README.md
> +Este proyecto tratará de facilitar la compra y venta de estos artículos utilizándose como intermediario y analizando la procedencia del producto.
El uso de una palabra mágica no te va a dar o quitar lógica de negocio. Lo importante es que entiendas el concepto de lógica de negocio y expliques claramente qué es "validar" y de qué forma consiste en una lógica de negocio no trivial que aporta valor a tu aplicación.

2021-10-04 17:12 UTC, JJ requested changes
Aclara las cuestiones que te pregunto, por favor.

2021-10-04 17:12 UTC, JJ commented on README.md
> +Por una parte, calculará el rendimiento máximo que se le puede sacar al producto.
¿De qué forma esto se trata de un proyecto que se pueda llevar a cabo en la nube o la nube pueda aportar algo al mismo? ¿Qué problema resuelve y de quién? Siendo ese cálculo, evidentemente, una lógica de negocio suficiente, ¿entiendes que esto tendrías que programarlo y por tanto saber cómo se calcula y en base a qué?

2021-10-04 17:31 UTC, francisco3207 commented on README.md
> +Por una parte, calculará el rendimiento máximo que se le puede sacar al producto.
La aplicación resolvería la incertidumbre de cada año de saber cuanto vale y encontrar el mejor momento para vender, permitiéndote negociar con la cooperativa o un comprador un mejor precio.
Vengo de una familia que se dedica a ello y se puede calcular y predecir aproximadamente.

2021-10-04 17:34 UTC, JJ commented on README.md
> +Por una parte, calculará el rendimiento máximo que se le puede sacar al producto.
OK. Acláralo en el fichero y creo que el objetivo estará superado, siempre que aclares también qué beneficio puede venir de estar en la nube y de tener múltiples usuarios (que es de lo que se trata, entre otras cosas, la nube)

2021-10-05 10:08 UTC, JJ approved these changes
OK, voy a suponer que la lógica de negocio va más allá de multiplicar varias cantidades y que por tanto el objetivo está superado.

2021-10-05 12:25 UTC, merged