[IV-21-22] Objetivo 2
francisco3207/IVProyecto pull request #11
Opened 2021-12-01 19:17 UTC by morevi

En este PR trataré de hacer avanzar [M0](https://github.com/francisco3207/IVProyecto/milestone/2).
- Continúa #7
- #9, relacionado con la HU anterior.
- #10

2021-12-02 08:44 UTC, morevi commented
Esperando review @francisco3207

2021-12-05 22:54 UTC, morevi commented
@JJ Listo para revisión!

2021-12-06 19:30 UTC, francisco3207 reviewed
En calcular_beneficio podrias añadir el precio total segun los meses del año con respecto a otros años.

2021-12-07 11:42 UTC, JJ requested changes
El issue #9 no plantea ningún problema de forma realista, y la resolución en una sola clase no sigue el principio de "separation of concerns", una clase debe hacer una sola cosa.

2021-12-07 11:42 UTC, JJ commented on docs/clase_producto.md
> +Para representar los cultivos, se ha creado una clase _producto_.
Esto debe estar en un issue, no aquí.

2021-12-07 11:42 UTC, JJ commented on producto/producto.py
> +    def __init__(self, tipo: str, rendimiento_base: float, fecha_plantado):
Estás mezclando la producción, que supongo que sería anual, con la producción anual. O algo así, no lo tengo muy claro. Deberías crear un issue para ver realmente qué es lo que necesita, y qué es lo que va a usarse en la lógica de negocio.

2021-12-08 16:57 UTC, morevi commented
@JJ Listo para revisión.
Se ha modificado el contenido de #9 para aclarar que se necesita, y creado #12. Se ha reformulado el issue como un problema.
Se ha separado en 2 clases con funcionalidad separada.

2021-12-09 10:56 UTC, francisco3207 approved these changes

2021-12-09 19:30 UTC, JJ approved these changes
El código que no falla es el que no se escribe, así que el enfoque minimalista puede servir, sobre todo si al jefe le parece bien. Va a ser más trabajo para @francisco3207 , sobre todo en el objetivo 4...

2021-12-09 19:31 UTC, JJ commented
A ver, @morevi , que no has hecho el PR al fichero...

2021-12-09 19:32 UTC, JJ requested changes
Retiro el OK hasta que no pase los tests en IV-21-22

2022-09-06 10:33 UTC, closed without merging